# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: flake8
      - id: check-docstring-first
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa
      - id: python-no-eval
      - id: rst-backticks
        exclude: docs/misc/coding-guidelines.rst
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.18.0
    hooks:
      - id: yamllint
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/haizaar/check-pipfile-lock
    rev: v0.0.1
    hooks:
      - id: check-pipfile-lock
        exclude: test
