language: python

python:
  - "3.7"  # Should be first as this is a default
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev
  - pip install -e .

jobs:
  include:
    - stage: lint
      script: pre-commit run --all-files
    - stage: test
      script: tests/test.sh
