language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev
  - pip install -e .

env:
  matrix:
    - LINT=yes
    - LINT=no

script:
  - if [[ "$LINT" == "yes" ]]; then pre-commit run --all-files; fi
  - tests/test.sh

matrix:
  exclude:
    - python: "3.6"
      env: LINT=yes
    - python: "3.7"
      env: LINT=no
